### ISSUE TITLE
Email issues

### ISSUE THREAD

**Issue by robertnixon2003** [harvard-itsecurity/docker-misp#2]
I am getting email errors with fetching GPG keys and when trying to email items. It states that the email was sent but not delivered. How do I fix this? Also what if my organization does not use GPG?

**Comment by aniss05** [comment]
I did change the address of both sql and misp server in both dockerfile and build.sh to my server address, but when i go to the web interface I get "Internal Server Error". Can you please help me with this issue?

**Comment by ventz** [comment]
@aniss05 Can you try with today's update - it should fix that.

@robertnixon2003 - did you setup a mail server? Otherwise email is all local. A default GPG key is needed for MISP to "function" correctly, but you don't really have to use it past that point.

**Comment by aniss05** [comment]
I tried like you suggested with the latest update and I am still getting this error, and when I open the error.log in my docker container, I get the following error:

2017-09-26 14:51:01 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1045] Access denied for user \'misp\'@\'localhost\' (using password: YES)',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(269): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(99): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(33): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2017-09-26 14:51:02 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1045] Access denied for user \'misp\'@\'localhost\' (using password: YES)',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(269): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(99): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(33): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}

**Comment by ventz** [comment]
@aniss05 I decided to go to a brand new environment and test this out -- it seems to work, so I think there might be something old/cached on your side.

Here's what I did:

```
0.) docker rmi harvarditsecurity/misp  # just to confirm there is nothing
1.) cd /tmp
2.) git clone https://github.com/harvard-itsecurity/docker-misp
3.) cd docker-misp
4.) Edit build.sh -> I changed the two MySQL lines:
 --build-arg MYSQL_ROOT_PASSWORD=TestDifferentPassword \
 --build-arg MYSQL_MISP_PASSWORD=YetAnotherPassword \
5.) ./build.sh #wait until done
6.) Now, setup your "DATA" dir. NOTE: On the mac, by default only "/Users", "/Volumes", "/private", and "/tmp" are directories that Docker will see. I added "/docker" and created it.
7.) mkdir -p /docker/DATA/misp-db/
8.) Create 2 scripts:
a.) run-init.sh
b.) run.sh

run-init.sh contains:

docker run -it --rm \
    -v /docker/DATA/misp-db:/var/lib/mysql \
    harvarditsecurity/misp /init-db

run.sh contains:

docker run -it -d \
    -p 443:443 \
    -p 80:80 \
    -p 3306:3306 \
    -v /docker/DATA/misp-db:/var/lib/mysql \
    harvarditsecurity/misp
9.) Now run the "run-init.sh" and wait. Once it's complete, run the "run.sh". Once that starts, verify that the docker process is running with "docker ps"
10.) In the browser, go to https://localhost and try to login:
Login: admin@admin.test
Password: admin
```

^ For me, that works perfectly. Please verify that these exact steps work for you.
Thanks.

**Comment by aniss05** [comment]
Thanks for your quick reply @ventz , I will try your suggestion and let you know. Hope it will work, thanks again.

**Comment by aniss05** [comment]
Thanks a lot @ventz, it finally worked ! I followed the same steps that you sent except for the steps where you have to set up the external volume path. First I tried the same like yours and it was not working, but then I noticed that the volume "/docker/DATA/misp-db" owner's was not the same as my user, I do not know why this was causing me issues but when I changed the path of the volume in my home path "~/docker/DATA/misp-db", it finally worked.

**Comment by ventz** [comment]
@aniss05 Great! I am glad it's working.
Closing the issue - if something else comes up, please feel free to ping me here.
